sudo: false
language: node_js
node_js: stable
os:
  - linux
  - osx
cache:
  directories:
    - ./node_modules
install:
  - npm install
  - npm install natives@1.1.6
  - npm install -g gulp@3.9.0
script:
  - gulp lint
